travis:
  secure:
    BINSTAR_TOKEN: M6HQLONqtyThfq3H6w6fXmTFHx9WL1gAHYYhKAOmxgADWvNZ/+y67OZUKWw1yjBJT/a0XOoM/xtlNrItiOi+1txnybj8PszwF5VPfIztTjV4TlT+XkoFnEzt1kTQciyLn7MCAIAQ6IWJTefThG17+HjxzNGCeh0mk0ljcewS/CZtW9bZs75juymSxTvErBO6gkkCsWbQCYrftRJyZpvyaNnSGXy9EcN/3uvrXkSXuMjuAcER4qva5m8kypGe7f0dMv8LA2ec8PhTKTi65QXrc1XE/3AnydHukjmSxiqhp6PQcwpM3llDaDVP1K/OvBrX0GzxwnaNz3azfox0hQR9VzfWOYlYQ3XJI3fnIHsXoXSSScJ8Df2eB47ywSMolS6aJky7JtAd0E7XGoXFTc/K2NRFTP6WfvJuUPgAoA8eisq2yueQhvz3k/4dbREMZnmex6P2p1kwdReti83Y0B2angSttCsHypRqzsy0Ub+oaFCn4ItP+RwSDC1d4ljI+ody6sl+MRxedOxHC6Zh47+tjzRlQr8L59NjJhDeumgIFTLx2st55kdIHICx1Fr4vFKz8fWIVHJ+B19RPl/9Kx3ICea/cNVQPZXb/1nWbf6j6jOdsUEvCp5FnofAUyLt0Qt5YE1KeN/TNu1Iy5dOaCgSN0xEw4yGYXrehBhP8Y34al8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
